export const PRICES = {
  GAG: {
    name: "Grow a Garden",
    items: [
      { label: "Headless Horseman", price: 4 },
      { label: "Tiger", price: 4 },
      { label: "Golden Goose", price: 4 },
      { label: "Lobster Thermidor", price: 4 },
      { label: "French Fry Ferret", price: 4 },
      { label: "Corrupted Kitsune", price: 4 },
      { label: "Kitsune", price: 15 },
      { label: "Spinosaurus", price: 6 },
      { label: "Fennec Fox", price: 7 },
      { label: "Mimic Octopus", price: 5 },
      { label: "Disco Bee", price: 7 },
      { label: "Butterfly", price: 5 },
      { label: "Queen Bee", price: 4 },
      { label: "Raccoon", price: 10 },
      { label: "Ruby Squid", price: 4 },
      { label: "Dilophosaurus", price: 4 },
      { label: "Brontosaurus", price: 6 },
      { label: "Seal", price: 4 },
      { label: "Bald Eagle", price: 4 },
      { label: "Cockatrice", price: 5 },
      { label: "Hex Serpent", price: 4 },
      { label: "Elephant", price: 5 },
      { label: "Swan", price: 5 },
      { label: "Bearded Dragon", price: 4 },
      { label: "Goat", price: 5 },
      { label: "Wendigo", price: 6 },
      { label: "Peacock", price: 4 },
      { label: "New Year's Dragon", price: 5 },
      { label: "Diamond Panther", price: 4 },
      { label: "Mummy", price: 7 },
      { label: "Frost Dragon", price: 5 },
      { label: "Titanic Echo Frog", price: 25 },
      { label: "Titanic NM Peacock", price: 50 },
      { label: "RBH Dilophosaurus", price: 78 },
      { label: "1,000 Tokens", price: 14 },
      { label: "10,000 Tokens", price: 100 }
    ]
  },

  PVB: {
    name: "Plants v Brainrots",
    items: [
      { label: "3 King Limone", price: 1 },
      { label: "15 King Limone", price: 4 },
      { label: "50 King Limone", price: 10 },
      { label: "Troll Mango", price: 10 },
      { label: "Avocado", price: 17 },
      { label: "Glacial Lily", price: 10 },
      { label: "100k-200k DPS Plant", price: 3 },
      { label: "300k-400k DPS Plant", price: 5 },
      { label: "8-11M DPS Plant", price: 15 }
    ]
  },

  MM2: {
    name: "Murder Mystery 2",
    items: [
      { label: "Gingerscope", price: 188 },
      { label: "Traveler's Set", price: 170 },
      { label: "Luger", price: 5 },
      { label: "Celestial Set", price: 70 },
      { label: "Bauble", price: 19 },
      { label: "IceBreaker", price: 5 },
      { label: "Heartblade", price: 5 },
      { label: "Watergun", price: 5 },
      { label: "IcePiercer", price: 11 },
      { label: "Harvester", price: 12 },
      { label: "Dark Set", price: 32 },
      { label: "Vampire Set", price: 40 },
      { label: "Rainbow Set", price: 12 },
      { label: "Sakura Set", price: 30 },
      { label: "Borealis Set", price: 6 },
      { label: "Corrupt", price: 16 },
      { label: "Candleflame", price: 4 },
      { label: "ElderWood Set", price: 7 },
      { label: "Ornament", price: 2 },
      { label: "Bat", price: 6 },
      { label: "Candy Set", price: 7 },
      { label: "Snowcannon", price: 6 },
      { label: "Alienbeam Set", price: 25 },
      { label: "Bloom Set", price: 10 },
      { label: "Turkey", price: 28 },
      { label: "Snowstorm", price: 6 },
      { label: "Spectre Set", price: 5 },
      { label: "Swirly Axe", price: 3 },
      { label: "Soul Set", price: 12 },
      { label: "Batwing", price: 3 },
      { label: "Xeno Set", price: 10 },
      { label: "Light Bringer", price: 3 },
      { label: "Dark Bringer", price: 3 },
      { label: "Waves", price: 5.5 },
      { label: "Sunset", price: 5.5 },
      { label: "Everset", price: 90 }
    ]
  },

  SAB: {
    name: "Steal a Brainrot",
    items: [
      { label: "Strawberry Elephant", price: 900 },
      { label: "Meowl", price: 690 },
      { label: "Dragon Cannelloni", price: 95 },
      { label: "Garama & Madundung", price: 25 },
      { label: "Burguro & Fryuro", price: 30 },
      { label: "Ketupat Kepat", price: 11 },
      { label: "Ketchuru & Musturu", price: 12 },
      { label: "Esok Sekolah", price: 5 },
      { label: "Orcaledon", price: 6 },
      { label: "La Secret", price: 17 },
      { label: "Reinito Sleighito", price: 25 },
      { label: "Cooki & Milki", price: 32 },
      { label: "Fragrama & Chocrama", price: 30 },
      { label: "Los Puggies", price: 6 },
      { label: "La Jolly Grande", price: 9 },
      { label: "Money Reindeer", price: 5 },
      { label: "Spaghetti Tualetti", price: 12 },
      { label: "Spooky & Pumpky", price: 24 },
      { label: "Los Hotspotsitos", price: 9 },
      { label: "La Spooky Grande", price: 10 },
      { label: "Los Combinaisonas", price: 5 },
      { label: "Los 67", price: 5 },
      { label: "Lavadorito Spinito", price: 14 },
      { label: "La Ginger Sekolah", price: 8 },
      { label: "Mieteteira Bicycleteira", price: 5 },
      { label: "Esok Sekolah 90M/s", price: 7 },
      { label: "Esok Sekolah 100M-200M/s", price: 10 },
      { label: "Swaggy Bros 200M-300M/s", price: 15 },
      { label: "Los Combinasionas 100M-200M/s", price: 9 }
    ]
  },

  PS99: {
    name: "Pet Simulator 99",
    items: [
      { label: "1B Gems", price: 3.5 },
      { label: "2B Gems", price: 7 },
      { label: "3B Gems", price: 10 },
      { label: "4B Gems", price: 13 },
      { label: "5B Gems", price: 16 },
      { label: "6B Gems", price: 19 },
      { label: "7B Gems", price: 22 },
      { label: "8B Gems", price: 25 },
      { label: "9B Gems", price: 28 },
      { label: "10B Gems", price: 31 },
      { label: "15B Gems", price: 46 },
      { label: "20B Gems", price: 61 },
      { label: "25B Gems", price: 76 },
      { label: "30B Gems", price: 91 },
      { label: "40B Gems", price: 121 },
      { label: "50B Gems", price: 151 },
      { label: "1 Titanic", price: 25 },
      { label: "2 Titanics", price: 40 },
      { label: "3 Titanics", price: 60 },
      { label: "4 Titanics", price: 80 },
      { label: "5 Titanics", price: 100 }
    ]
  },

  BB: {
    name: "Blade Ball",
    items: [
      { label: "1K Tokens", price: 7.5 },
      { label: "5K Tokens", price: 35 },
      { label: "10K Tokens", price: 70 },
      { label: "20K Tokens", price: 140 },
      { label: "30K Tokens", price: 210 },
      { label: "40K Tokens", price: 278 },
      { label: "50K Tokens", price: 368 }
    ]
  }
};
