// config/prices.js

export const roles = {
  GAG: "1460735559977664542",
  GrowAGarden: "1460735391903776828",
  BladeBall: "1460735703704014849",
  PetSim99: "1460735768053154103",
  MM2: "1460735631323037706",
  StealABrainrot: "1460735482789892127",
};

export const prices = {
  GAG: [
    { name: "Headless Horseman", price: 4 },
    { name: "Tiger", price: 4 },
    { name: "Golden Goose", price: 4 },
    { name: "Lobster Thermidor", price: 4 },
    { name: "French Fry Ferret", price: 5 },
    { name: "Corrupted Kitsune", price: 4 },
    { name: "Kitsune", price: 15 },
    { name: "Spinosaurus", price: 6 },
    { name: "Fennec Fox", price: 7 },
    { name: "Mimic Octopus", price: 5 },
    { name: "Disco Bee", price: 7 },
    { name: "Butterfly", price: 5 },
    { name: "Queen Bee", price: 4 },
    { name: "Raccoon", price: 10 },
    { name: "Ruby Squid", price: 4 },
    { name: "Dilophosaurus", price: 4 },
    { name: "Brontosaurus", price: 6 },
    { name: "Seal", price: 4 },
    { name: "Bald Eagle", price: 4 },
    { name: "Cockatrice", price: 5 },
    { name: "Hex Serpent", price: 4 },
    { name: "Elephant", price: 5 },
    { name: "Swan", price: 5 },
    { name: "Bearded Dragon", price: 4 },
    { name: "Goat", price: 5 },
    { name: "Wendigo", price: 6 },
    { name: "Peacock", price: 4 },
    { name: "New Year's Dragon", price: 5 },
    { name: "Diamond Panther", price: 4 },
    { name: "Mummy", price: 7 },
    { name: "Frost Dragon", price: 5 },
    { name: "Titanic Echo Frog 15s CD", price: 25 },
    { name: "Titanic NM Peacock 15s CD", price: 50 },
    { name: "RBH Dilophosaurus", price: 78 },
    { name: "1,000 Tokens", price: 14 },
    { name: "10,000 Tokens", price: 100 },
  ],

  GrowAGarden: [
    { name: "3 King Limone", price: 1 },
    { name: "15 King Limone", price: 4 },
    { name: "50 King Limone", price: 10 },
    { name: "Troll Mango", price: 10 },
    { name: "Avocado", price: 17 },
    { name: "Glacial Lily", price: 10 },
    { name: "100k-200k DPS Plant", price: 3 },
    { name: "300k-400k DPS Plant", price: 5 },
    { name: "8-11M DPS Plant", price: 15 },
  ],

  BladeBall: Array.from({ length: 50 }, (_, i) => {
    const k = i + 1;
    const price = k <= 45 ? k * 7 : k <= 50 ? 5 + (k * 7) : k * 7;
    return { name: `${k}K Tokens`, price: price };
  }),

  PetSim99: [
    { name: "1B Gems", price: 3.5 },
    { name: "2B Gems", price: 7 },
    { name: "3B Gems", price: 10 },
    { name: "4B Gems", price: 13 },
    { name: "5B Gems", price: 16 },
    { name: "6B Gems", price: 19 },
    { name: "7B Gems", price: 22 },
    { name: "8B Gems", price: 25 },
    { name: "9B Gems", price: 28 },
    { name: "10B Gems", price: 31 },
    { name: "11B Gems", price: 34 },
    { name: "12B Gems", price: 37 },
    { name: "13B Gems", price: 40 },
    { name: "14B Gems", price: 43 },
    { name: "15B Gems", price: 46 },
    { name: "16B Gems", price: 49 },
    { name: "17B Gems", price: 52 },
    { name: "18B Gems", price: 55 },
    { name: "19B Gems", price: 58 },
    { name: "20B Gems", price: 61 },
    { name: "25B Gems", price: 76 },
    { name: "30B Gems", price: 91 },
    { name: "35B Gems", price: 106 },
    { name: "40B Gems", price: 121 },
    { name: "50B Gems", price: 151 },
    { name: "1 Titanic", price: 25 },
    { name: "2 Titanics", price: 40 },
    { name: "3 Titanics", price: 60 },
    { name: "4 Titanics", price: 80 },
    { name: "5 Titanics", price: 100 },
  ],

  MM2: [
    { name: "Gingerscope", price: 188 },
    { name: "Traveler's Set", price: 170 },
    { name: "Luger", price: 5 },
    { name: "Celestial Set", price: 70 },
    { name: "Bauble", price: 19 },
    { name: "IceBreaker", price: 5 },
    { name: "Heartblade", price: 5 },
    { name: "Watergun", price: 5 },
    { name: "IcePiercer", price: 11 },
    { name: "Harvester", price: 12 },
    { name: "Dark Set", price: 32 },
    { name: "Vampire Set", price: 40 },
    { name: "Rainbow Set", price: 12 },
    { name: "Sakura Set", price: 30 },
    { name: "Borealis Set", price: 6 },
    { name: "Corrupt", price: 16 },
    { name: "Candleflame", price: 4 },
    { name: "ElderWood Set", price: 7 },
    { name: "Ornament", price: 2 },
    { name: "Bat", price: 6 },
    { name: "Candy Set", price: 7 },
    { name: "Snowcannon", price: 6 },
    { name: "Alienbeam Set", price: 25 },
    { name: "Bloom Set", price: 10 },
    { name: "Turkey", price: 28 },
    { name: "Snowstorm", price: 6 },
    { name: "Spectre Set", price: 5 },
    { name: "Swirly Axe", price: 3 },
    { name: "Soul Set", price: 12 },
    { name: "Batwing", price: 3 },
    { name: "Xeno Set", price: 10 },
    { name: "Light Bringer", price: 3 },
    { name: "Dark Bringer", price: 3 },
    { name: "Waves", price: 5.5 },
    { name: "Sunset", price: 5.5 },
    { name: "Everset", price: 90 },
  ],

  StealABrainrot: [
    { name: "Strawberry Elephant", price: 900 },
    { name: "Meowl", price: 690 },
    { name: "Dragon Cannelloni", price: 95 },
    { name: "Garama & Madundung", price: 25 },
    { name: "Burguro & Fryuro", price: 30 },
    { name: "Ketupat Kepat", price: 11 },
    { name: "Ketchuru & Musturu", price: 12 },
    { name: "Esok Sekolah", price: 5 },
    { name: "Orcaledon", price: 6 },
    { name: "La Secret", price: 17 },
    { name: "Reinito Sleighito", price: 25 },
    { name: "Cooki & Milki", price: 32 },
    { name: "Fragrama & Chocrama", price: 30 },
    { name: "Los Puggies", price: 6 },
    { name: "La Jolly Grande", price: 9 },
    { name: "Money Reindeer", price: 5 },
    { name: "Spaghetti Tualetti", price: 12 },
    { name: "Spooky & Pumpky", price: 24 },
    { name: "Los Hotspotsitos", price: 9 },
    { name: "La Spooky Grande", price: 10 },
    { name: "Los Combinaisonas", price: 5 },
    { name: "Los 67", price: 5 },
    { name: "Lavadorito Spinito", price: 14 },
    { name: "La Ginger Sekolah", price: 8 },
    { name: "Mieteteira Bicycleteira", price: 5 },
    { name: "Esok Sekolah 90M/s", price: 7 },
    { name: "Esok Sekolah 100M-200M/s", price: 10 },
    { name: "Swaggy Bros 200M-300M/s", price: 15 },
    { name: "Los Combinasionas 100M-200M/s", price: 9 },
  ],
};
